Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    fc1:
      Precision:
        bias: fixed<6,1,TRN,WRAP,0>
        result: fixed<16,6>
        weight: fixed<6,1,TRN,WRAP,0>
      Trace: false
    fc1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    fc1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    fc2:
      Precision:
        bias: fixed<6,1,TRN,WRAP,0>
        result: fixed<16,6>
        weight: fixed<6,1,TRN,WRAP,0>
      Trace: false
    fc2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    fc3:
      Precision:
        bias: fixed<6,1,TRN,WRAP,0>
        result: fixed<16,6>
        weight: fixed<6,1,TRN,WRAP,0>
      Trace: false
    fc3_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        bias: fixed<6,1,TRN,WRAP,0>
        result: fixed<16,6>
        weight: fixed<6,1,TRN,WRAP,0>
      Trace: false
    output_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
      Trace: false
    relu2:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
      Trace: false
    relu3:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
      Trace: false
    softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
      exp_table_t: ap_fixed<18,8>
      inv_table_t: ap_fixed<18,4>
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_3/hls4ml_prj/keras_model.keras'
OutputDir: model_3/hls4ml_prj
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: f3B3eBfA
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
