Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    Precision: ap_int<6>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4mlprj_extensions_Quartus/keras_model.keras'
OutputDir: hls4mlprj_extensions_Quartus
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: a5afAffA
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
